#!/usr/bin/env python3
import unicodedata
from pathlib import Path

PINNED_UNICODE_VERSION = "15.0.0"
CATEGORIES = (
    "Lu", "Ll", "Lt", "Lm", "Lo", "Mn", "Mc", "Me",
    "Nd", "Nl", "No", "Pc", "Pd", "Ps", "Pe", "Pi", "Pf",
    "Po", "Sm", "Sc", "Sk", "So", "Zs", "Zl", "Zp",
    "Cc", "Cf", "Cs", "Co", "Cn",
)

if unicodedata.unidata_version != PINNED_UNICODE_VERSION:
    raise SystemExit(
        f"need Unicode {PINNED_UNICODE_VERSION}, got {unicodedata.unidata_version}"
    )

ranges = []
start = previous = None
category = None
for codepoint in range(0x110000):
    current = unicodedata.category(chr(codepoint))
    if current == "Cn":
        if start is not None:
            ranges.append((start, previous, category))
            start = previous = category = None
        continue
    if current != category or previous is None or codepoint != previous + 1:
        if start is not None:
            ranges.append((start, previous, category))
        start = codepoint
        category = current
    previous = codepoint
if start is not None:
    ranges.append((start, previous, category))

out = [
    "// Generated by scripts/gen-unicode-categories.py using Unicode 15.0.0.",
    "pub const Range = struct { first: u21, last: u21, category: u5 };",
    "pub const ranges = [_]Range{",
]
for first, last, name in ranges:
    out.append(
        f"    .{{ .first = 0x{first:X}, .last = 0x{last:X}, "
        f".category = {CATEGORIES.index(name)} }},"
    )
out.extend(
    [
        "};",
        "",
        "pub fn category(codepoint: u21) u5 {",
        "    var low: usize = 0;",
        "    var high: usize = ranges.len;",
        "    while (low < high) {",
        "        const middle = low + (high - low) / 2;",
        "        const range = ranges[middle];",
        "        if (codepoint < range.first) {",
        "            high = middle;",
        "        } else if (codepoint > range.last) {",
        "            low = middle + 1;",
        "        } else {",
        "            return range.category;",
        "        }",
        "    }",
        "    return 29;",
        "}",
        "",
    ]
)
Path("src/schema/unicode_categories.zig").write_text("\n".join(out))
